  const Adata = {
    allItems: [
       
          {
            id: 29,
            name: "Pact",
            category: "Pajamas",
            gender: "Women",
            cover: "./images/pact/womens pajamas/1.jpg",
            price:10,
          },
        {
            id: 19,
            name: "Patagonia",
            category: "Shirt",
            gender: "Men",
            cover: "./images/PATAGONIA/mens shirt/1.jpg",
            price: 100,
          },
          {
            id: 30,
            name: "Pact",
            category: "Pajamas",
            gender: "Women",
            cover: "./images/pact/womens pajamas/1.jpg",
            price:10,
          },
        {
            id: 15,
            name: "Patagonia",
            category: "Sweater",
            gender: "Women",
            cover: "./images/quince/women cardigan/2.jpg",
            price:10,
          },
          {
            id: 31,
            name: "Pact",
            category: "Pajamas",
            gender: "Women",
            cover: "./images/pact/womens pajamas/1.jpg",
            price:10,
          },
        {
            id: 14,
            name: "Patagonia",
            category: "Sweater",
            gender: "Women",
            cover:  "./images/quince/women cardigan/1.jpg",
            price:10,
          },
  
      {
        id: 1,
        name: "Patagonia",
        category: "Jacket",
        gender: "Men",
        cover: "./images/PATAGONIA/mens jacket/11.jpg",
        price: 100,
      },
      {
        id: 2,
        name: "H&M",
        category: "Shirt",
        gender: "Men",
        cover: "./images/H&M/MENS SHIRT/1.jpg",
        price: 30,
      },
      {
        id: 16,
        name: "Patagonia",
        category: "Sweater",
        gender: "Women",
        cover: "./images/quince/women cardigan/3.jpg",
        price:10,
      },
      {
        id: 10,
        name: "Patagonia",
        category: "Jacket",
        gender: "Men",
        cover: "./images/PATAGONIA/mens jacket/2.jpg",
        price: 100,
      },
      {
        id: 3,
        name: "H&M",
        category: "Trouser",
        gender: "Men",
        cover: "./images/H&M/MENS TROUSER/1.jpg",
        price: 50,
      },
      {
        id: 17,
        name: "Patagonia",
        category: "Sweater",
        gender: "Women",
        cover:  "./images/quince/women cardigan/2.jpg",
        price:10,
      },
      {
        id: 11,
        name: "Patagonia",
        category: "Jacket",
        gender: "Men",
        cover: "./images/PATAGONIA/mens jacket/3.jpg",
        price: 100,
      },
      {
        id: 18,
        name: "Patagonia",
        category: "Sweater",
        gender: "Women",
        cover: "./images/quince/women cardigan/5.jpg",
        price:10,
      },
      {
        id: 4,
       
        name: "Pact",
        category: "Pajamas",
        gender: "Women",
        cover: "./images/pact/womens pajamas/1.jpg",
        price: 100,
      },
      {
        id: 12,
        name: "Patagonia",
        category: "Jacket",
        gender: "Men",
        cover: "./images/PATAGONIA/mens jacket/4.jpg",
        price: 100,
      },
      {
        id: 5,
        name: "Pact",
        category: "Shirt",
        gender: "Men",
        cover: "./images/pact/mens shirt/1.jpg",
        price: 100,
      },
      {
        id: 13,
        name: "Patagonia",
        category: "Jacket",
        gender: "Men",
        cover: "./images/PATAGONIA/mens jacket/5.jpg",
        price: 100,
      },
      {
        id: 6,
        name: "Pact",
        category: "T-shirt",
        gender: "Women",
        cover: "./images/pact/womens t shirt/1.jpg",
        price: 20,
      },
      {
        id: 35,
        name: "Pact",
        category: "T-shirt",
        gender: "Men",
        cover: "./images/pact/mens t shirt/1.jpg",
        price: 20,
      },
      {
        id: 20,
        name: "Patagonia",
        category: "Shirt",
        gender: "Men",
        cover: "./images/PATAGONIA/mens shirt/2.jpg",
        price: 100,
      },
      {
        id: 32,
        name: "Pact",
        category: "T-shirt",
        gender: "Women",
        cover: "./images/pact/womens t shirt/2.jpg",
        price: 20,
      },
      {
        id: 36,
        name: "Pact",
        category: "T-shirt",
        gender: "Men",
        cover: "./images/pact/mens t shirt/2.jpg",
        price: 20,
      },
      {
        id: 7,
        name: "Quince",
        category: "Pants",
        gender: "Men",
        cover: "./images/quince/mens pants/1.jpg",
        price: 100,
      },
      {
        id: 39,
        name: "Quince",
        category: "Pants",
        gender: "Men",
        cover: "./images/quince/mens pants/2.jpg",
        price: 100,
      },
      {
        id: 40,
        name: "Quince",
        category: "Pants",
        gender: "Men",
        cover: "./images/quince/mens pants/3.jpg",
        price: 100,
      },
      {
        id: 41,
        name: "Quince",
        category: "Shirt",
        gender: "Men",
        cover: "./images/quince/mens shirt/2.jpg",
        price: 100,
      },
      {
        id: 42,
        name: "Quince",
        category: "Shirt",
        gender: "Men",
        cover: "./images/quince/mens shirt/3.jpg",
        price: 100,
      },
      {
        id: 33,
        name: "Pact",
        category: "T-shirt",
        gender: "Women",
        cover: "./images/pact/womens t shirt/3.jpg",
        price: 20,
      },
      {
        id: 8,
        name: "Quince",
        category: "cardigan",
        gender: "Women",
        cover: "./images/quince/women cardigan/1.jpg",
        price: 30,
      },
      {
        id: 34,
        name: "Pact",
        category: "T-shirt",
        gender: "Women",
        cover: "./images/pact/womens t shirt/4.jpg",
        price: 20,
      },
      {
        id: 9,
        name: "Reformation",
        category: "Jeans",
        gender: "Men",
        cover: "./images/reformation/mens jeans/1.jpg",
        price: 30,
      },
      {
        id: 43,
        name: "Reformation",
        category: "Jeans",
        gender: "Men",
        cover: "./images/reformation/mens jeans/2.jpg",
        price: 30,
      },
      {
        id: 24,
        name: "Patagonia",
        category: "T-shirt",
        gender: "Women",
        cover: "./images/pact/womens t shirt/3.jpg",
        price:10,
      },
      {
        id: 44,
        name: "Reformation",
        category: "Jeans",
        gender: "Men",
        cover: "./images/reformation/mens jeans/3.jpg",
        price: 30,
      },
      {
        id: 54,
        name: "Reformation",
        category: "Shirt",
        gender: "Men",
        cover: "./images/reformation/mens shirt/2.jpg",
        price: 30,
      },
      {
        id: 55,
        name: "Patagonia",
        category: "T-shirt",
        gender: "Women",
        cover: "./images/pact/womens t shirt/3.jpg",
        price:10,
      },
      {
        id: 45,
        name: "Reformation",
        category: "Shirt",
        gender: "Men",
        cover: "./images/reformation/mens shirt/3.jpg",
        price: 30,
      },
      {
        id: 21,
        name: "Patagonia",
        category: "Shirt",
        gender: "Men",
        cover: "./images/PATAGONIA/mens shirt/3.jpg",
        price: 100,
      },
      {
        id: 47,
        name: "Reformation",
        category: "Shirt",
        gender: "Men",
        cover: "./images/reformation/mens shirt/4.jpg",
        price: 30,
      },
      {
        id: 25,
        name: "Patagonia",
        category: "T-shirt",
        gender: "Women",
        cover: "./images/pact/womens t shirt/3.jpg",
        price:10,
      },{
        id: 26,
        name: "Patagonia",
        category: "T-shirt",
        gender: "Women",
        cover: "./images/pact/womens t shirt/5.jpg",
        price:10,
      },
      {
        id: 46,
        name: "Reformation",
        category: "Tops",
        gender: "Women",
        cover: "./images/reformation/womens tops/2.jpg",
        price: 30,
      },
      {
        id: 36,
        name: "Pact",
        category: "T-shirt",
        gender: "Men",
        cover: "./images/pact/mens t shirt/3.jpg",
        price: 20,
      },
      {
        id: 22,
        name: "Patagonia",
        category: "Shirt",
        gender: "Men",
        cover: "./images/PATAGONIA/mens shirt/4.jpg",
        price: 20,
      },
      {
        id: 48,
        name: "Reformation",
        category: "Tops",
        gender: "Women",
        cover: "./images/reformation/womens tops/3.jpg",
        price: 30,
      },
      {
        id: 37,
        name: "Pact",
        category: "T-shirt",
        gender: "Men",
        cover: "./images/pact/mens t shirt/5.jpg",
        price: 20,
      },
      {
        id: 38,
        name: "Quince",
        category: "cardigan",
        gender: "Women",
        cover: "./images/quince/women cardigan/2.jpg",
        price: 30,
      },
      {
        id: 49,
        name: "Reformation",
        category: "Tops",
        gender: "Women",
        cover: "./images/reformation/womens tops/4.jpg",
        price: 30,
      },
      {
        id: 39,
        name: "Quince",
        category: "cardigan",
        gender: "Women",
        cover: "./images/quince/women cardigan/3.jpg",
        price: 30,
      },
      {
        id: 40,
        name: "Quince",
        category: "cardigan",
        gender: "Women",
        cover: "./images/quince/women cardigan/5.jpg",
        price: 30,
      },
      {
        id: 50,
        name: "Reformation",
        category: "Tops",
        gender: "Women",
        cover: "./images/reformation/womens tops/5.jpg",
        price: 30,
      },
      {
        id: 23,
        name: "Patagonia",
        category: "Shirt",
        gender: "Men",
        cover: "./images/PATAGONIA/mens shirt/5.jpg",
        price: 10,
      },
    ]
  }
  export default Adata
  
